[package]
name = "coconut_crab_client"
version.workspace = true
edition.workspace = true
build = "build.rs"
description = "Simulated ransomware client for incident response testing"
license.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true

[package.metadata.winresource]
ProductName = "Coconut Crab"
OriginalFilename = "coconut_crab_client.exe"
FileDescription = "Mary-Kate and Ashley"
LegalCopyright = "jenkinsmichpa"

[dependencies]
coconut_crab_lib = { workspace = true }
auto-launch = { workspace = true }
hex = { workspace = true }
rand = { workspace = true }
purecrypto = { workspace = true, features = ["rsa", "cipher", "der", "std"] }
zeroize = { workspace = true }
serde = { workspace = true }
csv = { workspace = true }
hostname = { workspace = true }
litcrypt2 = { workspace = true }
log = { workspace = true }
rust-embed = { workspace = true, features = ["include-exclude"] }
slint = { workspace = true, features = [
  "std",
  "backend-winit",
  "renderer-software",
  "accessibility",
  "compat-1-2",
] }
image = { workspace = true, features = [
  "avif",
  "bmp",
  "dds",
  "ff",
  "gif",
  "hdr",
  "ico",
  "jpeg",
  "exr",
  "png",
  "pnm",
  "qoi",
  "tga",
  "tiff",
  "webp",
] }
env_logger = { workspace = true }
flume = { workspace = true }
regex = { workspace = true }
zip = { workspace = true, features = [
  "deflate-flate2-zlib-rs",
] }
wallpaper = { workspace = true }
zlob = { workspace = true }

[build-dependencies]
embed-manifest = { workspace = true }
winresource = { workspace = true }
slint-build = { workspace = true }

[lints]
workspace = true
