[package]
name = "group_docx_tool"
version = "0.1.0"
authors = ["Michael Jenkins <me@jenkinsmichpa.com>"]
edition = "2024"
description = "Generates and verifies randomish docx files for given group numbers"
license = "MIT"
repository = "https://github.com/jenkinsmichpa/coconut_crab"
readme = "../README.md"
keywords = ["docx", "education", "incident-response"]
categories = ["education", "security"]

[dependencies]
docx-rust = "0.1.11"
hex = "0.4.3"
rand = "0.10.2"
purecrypto = { version = "0.7.0", default-features = false, features = [
  "hash",
  "std",
] }
ureq = { version = "3.4.0", default-features = false, features = ["rustls"] }

[lints.clippy]
correctness = { level = "warn", priority = -1 }
perf = { level = "warn", priority = -1 }
complexity = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }
nursery = { level = "warn", priority = -1 }
style = { level = "warn", priority = -1 }
