[package]
name = "coconut_crab_lib"
version = "0.1.0"
authors = ["Michael Jenkins <me@jenkinsmichpa.com>"]
edition = "2024"
description = "Library for coconut_crab packages"
license = "MIT"
repository = "https://github.com/jenkinsmichpa/coconut_crab"
readme = "../README.md"
keywords = [
  "ransomware",
  "simulation",
  "incident-response",
  "education",
  "security",
]
categories = ["simulation", "security"]

[dependencies]
serde = { workspace = true }
regex = { workspace = true }
log = { workspace = true }
rust-embed = { workspace = true, features = ["include-exclude"] }
ureq = { workspace = true, features = ["json", "rustls"] }
hex = { workspace = true }
purecrypto = { workspace = true, features = ["hash", "std"] }
litcrypt2 = "0.1.3"

[lints]
workspace = true
