[package]
name = "coconut_crab_lib"
version.workspace = true
edition.workspace = true
description = "Library for coconut_crab packages"
license.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
serde = { workspace = true }
regex = { workspace = true }
log = { workspace = true }
rust-embed = { workspace = true, features = ["include-exclude"] }
ureq = { workspace = true, features = ["json", "rustls"] }
hex = { workspace = true }
purecrypto = { workspace = true, features = ["hash", "std"] }
litcrypt2 = { workspace = true }

[lints]
workspace = true
